CREATE TABLE MEDECIN(
ID_MEDECIN INT PRIMARY KEY NOT NULL ,
NOM_MEDECIN VARCHAR2(20) NOT NULL ,
PRENOM_MEDECIN VARCHAR2(20) NOT NULL ,
ADRESSE_MEDECIN VARCHAR2(50) NOT NULL,
SPECIALITE_MEDECIN VARCHAR2(20) NOT NULL,
USERNAME VARCHAR2(25) NOT NULL UNIQUE,
PASSWORD VARCHAR2(25) NOT NULL
);
CREATE TABLE PATIENT(
ID_PATIENT int PRIMARY KEY NOT NULL ,
NOM_PATIENT VARCHAR2(20) NOT NULL ,
PRENOM_PATIENT VARCHAR2(20) NOT NULL ,
ADRESSE_PATIENT VARCHAR2(50) NOT NULL,
AGE_PATIENT INT NOT NULL,
SEXE VARCHAR2(1) NOT NULL,
TELEPHONE INT NOT NULL
);
CREATE TABLE SECRETAIRE(
ID_SECRETAIRE INT PRIMARY KEY NOT NULL ,
NOM_SECRETAIRE VARCHAR2(20) NOT NULL ,
PRENOM_SECRETAIRE VARCHAR2(20) NOT NULL ,
USERNAME VARCHAR2(25) NOT NULL UNIQUE,
PASSWORD VARCHAR2(25) NOT NULL
);
CREATE TABLE RENDEZ_VOUS(
ID_SECRETAIRE INT NOT NULL,
ID_PATIENT INT NOT NULL,
ID_MEDECIN INT NOT NULL,
DATE_RENDEZ_VOUS DATE NOT NULL,
HEURE INT NOT NULL,
MINUTES INT NOT NULL,
CONSTRAINT PK_RENDEZ_VOUS PRIMARY KEY (ID_MEDECIN,DATE_RENDEZ_VOUS,HEURE,MINUTES),
CONSTRAINT FK_ID_SECRETAIRE_RENDEZ_VOUS FOREIGN KEY (ID_SECRETAIRE) REFERENCES SECRETAIRE(ID_SECRETAIRE),
CONSTRAINT FK_ID_PATIENT_RENDEZ_VOUS FOREIGN KEY (ID_PATIENT) REFERENCES PATIENT(ID_PATIENT),
CONSTRAINT FK_ID_MEDECIN_RENDEZ_VOUS FOREIGN KEY (ID_MEDECIN) REFERENCES MEDECIN(ID_MEDECIN)
);
CREATE TABLE MEDICAMENT(
ID_MEDICAMENT INT NOT NULL ,
NOM_MEDICAMENT VARCHAR2(20) NOT NULL,
CONSTRAINT PK_MEDICAMENT PRIMARY KEY (ID_MEDICAMENT)
);
CREATE TABLE ORDONANCE(
ID_ORDONANCE INT NOT NULL ,
ID_PATIENT INT NOT NULL,
DATE_RENDEZ_VOUS DATE,
CONSTRAINT PK_ORDONANCE PRIMARY KEY (ID_ORDONANCE),
CONSTRAINT FK_ID_PATIENT_ORDONANCE FOREIGN KEY (ID_PATIENT) REFERENCES PATIENT(ID_PATIENT)
);
CREATE TABLE AVOIR(
ID_ORDONANCE INT NOT NULL,
ID_MEDICAMENT INT NOT NULL,
ID_PATIENT INT NOT NULL,
CONSTRAINT PK_AVOIR PRIMARY KEY (ID_ORDONANCE,ID_MEDICAMENT,ID_PATIENT),
CONSTRAINT FK_ID_MEDICAMENT_AVOIR FOREIGN KEY (ID_MEDICAMENT) REFERENCES MEDICAMENT(ID_MEDICAMENT),
CONSTRAINT FK_ID_ORDONANCE_AVOIR FOREIGN KEY (ID_ORDONANCE) REFERENCES ORDONANCE(ID_ORDONANCE),
CONSTRAINT FK_ID_PATIENT_AVOIR FOREIGN KEY (ID_PATIENT) REFERENCES PATIENT(ID_PATIENT)
);
CREATE TABLE AVOIR2(
ID_MEDICAMENT INT NOT NULL,
DOSE INT NOT NULL,
NB_JOURS INT NOT NULL,
CONSTRAINT PK_AVOIR2 PRIMARY KEY (ID_MEDICAMENT,DOSE,NB_JOURS),
CONSTRAINT FK_ID_MEDICAMENT_AVOIR2 FOREIGN KEY (ID_MEDICAMENT) REFERENCES MEDICAMENT(ID_MEDICAMENT)
);
CREATE TABLE CONSULTATION(
ID_PATIENT INT NOT NULL,
ID_MEDECIN INT NOT NULL,
DATE_CONSULTATION DATE NOT NULL,
SYMPTOMES VARCHAR2(50) NOT NULL,
CONSTRAINT PK_CONSULTATION PRIMARY KEY (ID_PATIENT,ID_MEDECIN),
CONSTRAINT FK_ID_PATIENT_CONSULTATION FOREIGN KEY (ID_PATIENT) REFERENCES PATIENT(ID_PATIENT),
CONSTRAINT FK_ID_MEDECIN_CONSULTATION FOREIGN KEY (ID_MEDECIN) REFERENCES MEDECIN(ID_MEDECIN)
);
CREATE TABLE CERTIFICAT_MEDICAL(
CODE INT NOT NULL,
ID_PATIENT INT NOT NULL,
DATE_CERTIFICAT DATE NOT NULL,
TEXTE VARCHAR2(50) NOT NULL,
CONSTRAINT PK_CERTIFICAT_MEDICAL PRIMARY KEY (CODE,ID_PATIENT),
CONSTRAINT FK_ID_PATIENT_CERTIFICAT FOREIGN KEY (ID_PATIENT) REFERENCES PATIENT(ID_PATIENT)
);